branch-defaults:
  master:
    environment: Ebhostingafullstackapplication-env
global:
  application_name: EB-Hosting-a-Full-Stack-Application
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-1
  sc: git